name: in_app_purchases_intl
description: Intl Package for common translations in your In App Purchase App. made by www.linkfive.io
version: 1.0.1
homepage: https://github.com/LinkFive/flutter-in_app_purchases_paywall
repository: https://github.com/LinkFive/flutter-in_app_purchases_paywall

environment:
  sdk: ">=3.3.4"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  generate: true
